# Site settings
title: Ionic.io
email: help@ionic.io
description: "Docs for ionic.io"
baseurl: ""
name: Ionic.io Docs
url: "http://ionic.io"

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
